#! /bin/sh

bspc config border_width        4
bspc config window_gap          2

bspc config split_ratio         0.50
# Remove borders for tiled windows in monocle mode.
bspc config borderless_monocle  true
# Remove gaps for tiled windows in monocle mode.
bspc config gapless_monocle     true
# Base focusing on distances between windows.
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI

bspc config normal_border_color "#332d29"
bspc config active_border_color "#00E600"
bspc config focused_border_color "#00E600"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a mpv floating=on

bspc rule -a chromium desktop=^13
bspc rule -a zathura desktop=^14
bspc rule -a libreoffice desktop=^14

bspc rule -a Conky sticky=on manage=off lower=on

# bspc rule -a Skype desktop=^8
# bspc rule -a Firefox desktop=^12
# bspc rule -a qutebrowser desktop=^9

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

# 1-3:   . - main terminal
# 4-6:   / - scratch
# 7:     m - email
# 8:     i - skype (instant messenger)
# 9-11:  b - qutebrowser
# 12:    u - firefox

# 13:    y - chrome
# 14-16: o - documents

# Autostart
# @TODO: starting tmuxinator projects is ugly and brittle. Surely there must be
# a better way?
if [[ -z "$(xtitle)" ]]; then

    bspc rule --add Skype desktop=^8 --one-shot; skype >/dev/null 2>&1 &
    bspc rule --add qutebrowser desktop=^9 --one-shot; qutebrowser >/dev/null 2>&1 &
    bspc rule --add Firefox desktop=^12 --one-shot; firefox >/dev/null 2>&1 &

    bspc rule --add termite desktop='^1' --one-shot; termite >/dev/null 2>&1 &
    sleep 1
    tmux send-keys -t 0 'tmuxinator start main' Enter
    sleep 0.3

    bspc rule --add termite desktop='^4' --one-shot; termite >/dev/null 2>&1 &
    sleep 1
    tmux send-keys -t 1 'tmuxinator start scratch' Enter
    sleep 0.3

    bspc rule --add termite desktop='^7' --one-shot; termite >/dev/null 2>&1 &
    sleep 1
    tmux send-keys -t 2 'tmuxinator start mail' Enter
    sleep 0.3

    # Start from mail, it wants password
	bspc desktop --focus ^7

    sleep 0.1
    tmux kill-session -t 0
    tmux kill-session -t 1
    tmux kill-session -t 2
fi
