#! /bin/sh

bspc config border_width        4
bspc config window_gap          2

bspc config split_ratio         0.50
# Remove borders for tiled windows in monocle mode.
bspc config borderless_monocle  true
# Remove gaps for tiled windows in monocle mode.
bspc config gapless_monocle     true
# Base focusing on distances between windows.
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "#332d29"
bspc config active_border_color "#00E600"
bspc config focused_border_color "#00E600"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a mpv floating=on
bspc rule -a zathura desktop=^10
bspc rule -a Firefox desktop=^1
bspc rule -a Skype desktop=^3
bspc rule -a qutebrowser desktop=^4

bspc rule -a Conky sticky=on manage=off lower=on
